### ISSUE TITLE
VPN works, then disconnects after a few MB transferred.

### ISSUE THREAD

**Issue by EricTheRed1** [KaiserSoft/PIA-Tunnel#11] opened 2016-07-18 04:38 UTC
This issue only happened after the last update from 7-16-16.  I tried using the command "tail -f /pia/cache/session.log" but it says no such file or directory.  

It will eventually auto-reconnect but the gateway will be disabled. Restarting the firewall temporarily fixes this.

Thanks for the help

**Comment by KaiserSoft** [comment] 2016-07-18 15:16
Hello Eric,

the file is only available as long as the connection is active. So please run the command once the connection has been established.


Are you using "pia-daemon" by any chance? It could be that the list of IPs used to check if the connection is up is getting too old. 
You could try and generate a new one like this 
> rm /pia/ip_list.txt && /pia/include/build_ping_list.sh

**Comment by EricTheRed1** [comment] 2016-07-18 23:53
I ran the command to update the ip list and it ran just fine.  I have the same issue after the command was run.  I even turned off the pia-daemon and it shows that the vpn is connected but no data is flowing.  It only works for a few seconds and then stops.

**Comment by EricTheRed1** [comment] 2016-07-19 12:23
I just tried re-installing from scratch with VirtualBox.  Followed the documentation and it does the same thing as VMware Fusion.  Just works for a few seconds or so.

**Comment by KaiserSoft** [comment] 2016-07-19 12:41
Ahh which docu are you following right now for the installation?
The steps listed in "[from scratch] Debian 8 setup" are not working right now. I am in the process of releasing v2 but it is not done. I ran into a bug which delayed everything.

The only working system is the classic Debian 7 VM located here. http://www.kaisersoft.net/r/?PIAIMG

Any luck on the session.log file. This is where you will find a reason why the VPN has disconnected as this is generated by openVPN itself.

Alternatively you could try and connect by hand like so
cd /pia/ovpn/PIAtcp
openvpn Germany.ovpn

You will now see the output on the console. Try and download something and watch for any errors.

**Comment by EricTheRed1** [comment] 2016-07-19 12:53
I did download the VM with the link you provided so I should be using the classic Debian 7.  

I don't understand how to look at the session.log file after the command is run.

I tried connecting by hand but no data is being transferred that way.

**Comment by KaiserSoft** [comment] 2016-07-19 13:01
Ohh yes, woops. The firewall will not be active. Hold on I'll have to try something on my end.

**Comment by KaiserSoft** [comment] 2016-07-19 13:10
OK this should work.

reboot the VM so everything is fresh.
Login then run
> pia-start PIAtcp/Germany
and wait until it says VPN connection established

Now try
> tail -f /pia/cache/session.log
again. Does it show you the content this time? Now try and download something and watch the output

**Comment by EricTheRed1** [comment] 2016-07-19 13:18
Ok, it shows the log now.  Here's what i get [http://imgur.com/BBlC1U3](url)

**Comment by KaiserSoft** [comment] 2016-07-19 13:33
Mhh I see "Authentication/Decrypt packet error" which I can not reproduce.
You OpenVPN reports version 2.1 while mine says 2.2.1

You you please run
> openvpn --version

You will a bunch of text but only need to look at line 1. It should say "OpenVPN 2.2.1 i486-linux-gnu". Does it?

Are you using "PIA-Tunnel-release_php-gui-2015-03-16"? If not you could try a system update
> apt-get update
> apt-get upgrade

Now rebooot and try again. Better?

**Comment by EricTheRed1** [comment] 2016-07-19 13:44
it's saying in have openvpn 2.2.1.  I ran the update and upgrade commands.  Still have the same issue.  I did download the image from http://www.kaisersoft.net/r/?PIAIMG .  

Also, if i wait a bit the log says "resolve: cannot resolve host address: us-east.privateinternetaccess.com: [TRY_AGAIN] A temporary error occurred on an authorative name server."

**Comment by KaiserSoft** [comment] 2016-07-19 13:51
OK that suggest an issues resolving names. What happens when you do

>ping google.com
>ping us-east.privateinternetaccess.com

**Comment by EricTheRed1** [comment] 2016-07-19 14:04
Before it stops working i can ping google.  After it stops transferring files it does not ping anything.  Says unknown host.

**Comment by KaiserSoft** [comment] 2016-07-19 14:08
That is very odd. Never seen this behavior. Which version of Virtual Box and OS X are you using?

**Comment by KaiserSoft** [comment] 2016-07-19 14:27
Something else you could try is what happens when you go back to an older release.

> cd /pia
> git checkout -f 17072ab
> pia-setup

Will revert back to an older version .... just to find out if it is really caused by an update.

**Comment by KaiserSoft** [comment] 2016-07-19 17:11
Hey Eric,
been thinking about it for a bit more. Could you please describe your setup?
Are you running the VM on the same computer you use to access the VPN with?

Could you please check the IP of your computer after you are unable to connect to the Internet? The VM has a built in DHCP server. Depending on your setup, the DHCP server may hand out IPs on your LAN.

**Comment by EricTheRed1** [comment] 2016-07-19 21:20
You got me thinking about this more.  This has been on my mind all day at work.  I saw your message as I was heading back home.  I had a horrible IP misconfiguration issue.  It's actually quite embarrassing because I'm studying Cisco networking in college.  This is why you should not configure network configurations on no sleep.  

Moving on....the issue still persisted, so I did what you said and rolled back the version with your 17072ab command.  This seems to have fixed the issue.

Now, I'd rather not use the old version; so I'm happy to test out the new version with whatever guidance you have to offer.  If you want, you can remotely control my machine if you promise not to destroy me.

Here's my setup:
I'm using the MacOS Sierra public beta.  I'm on a hackintosh with 2 ethernet cards (another 2 not plugged in).  I tested out the newest version in both virtualbox and VMware fusion.  I had been using VMware fusion with your software for years with no issues.  My first ethernet card is connected to my router via DHCP and my second ethernet card is using an ip address on my router's subnet with a gateway ip of the VPN gateway (192.168.10.1).

Please let me know what I can do to help.  Thanks again

**Comment by KaiserSoft** [comment] 2016-07-20 07:30
> Moving on....the issue still persisted, so I did what you said and rolled back the version with your 17072ab command. This seems to have fixed the issue.

Crap, not what I wanted to hear :)
But this is good. Now we can narrow it down. There are not that many releases so if you please try going up one release at a time and see which one is the one that breaks it. 

> cd /pia
> git checkout -f a123751
> pia-setup

> cd /pia
> git checkout -f eef7d69
> pia-setup

> cd /pia
> git checkout -f a79be31
> pia-setup

> cd /pia
> git checkout -f 3da1d05
> pia-setup

> cd /pia
> git checkout -f 4028b10
> pia-setup

> cd /pia
> git checkout -f f775452
> pia-setup

This is going to be interesting.

**Comment by glberen** [comment] 2016-07-20 18:52
Mine has been disconnecting a lot as well, FYI. It would always disconnect sometimes, but failover to another endpoint without issue. Now when it fails, it just hangs at connecting. A restart of the VM allows it connect again...sometimes for a few minutes...sometimes for a few hours. It's hard to say whether it's the VM or the PIA connection, but I thought I'd convey this since it's perhaps related.

**Comment by glberen** [comment] 2016-07-20 19:17
Switching to UDP again seems to have helped perhaps.

**Comment by EricTheRed1** [comment] 2016-07-20 20:10
Ok, thank you for providing all the commands.  Version 4028b10 definitely breaks it.  Had to reboot the VM after each update.

**Comment by KaiserSoft** [comment] 2016-07-22 13:35
> Ok, thank you for providing all the commands. Version 4028b10 definitely breaks it. Had to reboot the VM after each update.

Well that sucks. Only thing that changed in 4028b10 is that the new openVPN files where added. One thing I don't understand is why it does not fail when I try to replicate the issue on my VM.
@glberen are you on OSX as well?

**Comment by glberen** [comment] 2016-07-22 13:56
I'm running the routing VM on Ubuntu 16.04. It's been solid since switching back to UDP. It may just be a PIA thing. I've noticed at times they get a bit disconnect happy, then I'll go weeks without being disconnected.

**Comment by KaiserSoft** [comment] 2016-07-22 14:15
Just deployed the VM on Virtual Box running on El Capitan. Setup the VM to share the VPN with the "Public LAN", connected to Germany and I am now at 90% of a 1GB test download file @1,84MB/s
http://www.thinkbroadband.com/download/

Are you guys running the VM on the same machine you use to download the files or is it a separate box?
My Testsetup is 

- Mac Mini with Virtual Box running the PIA-Tunnel VM (VPN GW enabled on Public IF [eth0])
- Windows VM running on my work Laptop, using the Public IP of PIA-Tunnel as the default Gateway

All Computers are set to DHCP. On the Windows System I had to manually delete delete the default route to override the default GW set by DHCP.


Test download just finished and the VPN is still up.

**Comment by KaiserSoft** [comment] 2016-07-22 14:32
> I'm running the routing VM on Ubuntu 16.04. It's been solid since switching back to UDP. It may just be a PIA thing. I've noticed at times they get a bit disconnect happy, then I'll go weeks without being disconnected. 

I used to have these issues with UDP, that's why I added TCP in the first place. Funny thing is that TCP can be faster a times .... for some reason.
The test download using PIAudp/Germany just finished without an error but the speed was about 400KB/s slower when compared to TCP. Used the same VPN connection point and file for the test.

I will sit down and rewrite "pia-daemon" once release-v2 is out. It is supposed to deal with dropped connections but it tends to fail when openVPN does not restore the default route.

**Comment by EricTheRed1** [comment] 2016-07-22 20:11
I'm running the VM on the same machine I'm using to download files.  It has worked well for me this way in the past.  No idea why it's not working now.

**Comment by KaiserSoft** [comment] 2016-07-26 12:58
Sorry for the delay. Been quite busy at work.

> I'm running the VM on the same machine I'm using to download files. It has worked well for me this way in the past. No idea why it's not working now.

I'll have to retest that scenario. I know that this can be a bit error prone when working with dynamic IPs but I doubt it is related since the patch causing the issues only changed the openVPN connection files.
I'll try to fix the "show stopper" bug in release-v2. Maybe you can try the new release, which is build on Debian 8, to see if the issue persists. I should have some time tomorrow to debug the issue

**Comment by KaiserSoft** [comment] 2016-08-02 13:58
Finally found the issue corrupting settings.conf in version 2. The version posted below should be fully functional.
You may download it here [release-v2-RC2](
https://mega.nz/#!LBwTTTzZ!4qn1o0panEJnhtn1_o_h6O5QnpNA-QQCunNlTQ9drCE
) 
It does not include vmware tools yet since I will probably write a webUI installer for the different VM solutions.


The UI is is pretty much the same but build on Debian 8. It also comes with the latest openVPN so providers such as iVPN should finally work. **This is only a release candidate!**
I still want to do things like packet sniffing and need to do final validation before I can turn this into an official release.

**Comment by EricTheRed1** [comment] 2016-08-03 04:42
Thank you for working on this issue for us.  I just downloaded the v2-RC2.  At first I wasn't sure it was working but then the ip address popped up after a minute.  It's doing something similar to the old image.  It transferred a few megabytes and then disconnected.  The browser interface just says internet down.  I tried to switch to TCP non-high for PIA and it won't reconnect.

**Comment by KaiserSoft** [comment] 2016-08-03 12:47
No idea since I can not replicate this issue in any way. I'll lookup the commands required to initiate the VPN connection using only openVPN. Might be time to contact PIA Support if the issue can be replicated that way.

**Comment by KaiserSoft** [comment] 2016-08-03 14:01
Hello Eric,
the following commands will set the log output of openVPN to "debug", initiate the VPN connection and turn port forwarding on. You will find the full log at /tmp/openvpn.log
**Careful, the log will contain your public IP.** Please send me a mail via my contact form and I'll send you my e-mail address so you can send me the log as an attachment.

Start by rebooting the VM. Navigate to the pia installation directory, /pia in release-v1 or /usr/local/pia in release-v2, and enter the commands from there.
> sed -i 's/verb 1/verb 6/g' ovpn/PIAtcp/Germany.ovpn
> echo "log /tmp/openvpn.log" >> ovpn/PIAtcp/Germany.ovpn
> openvpn ovpn/PIAtcp/Germany.ovpn &
> sleep 4 && pia-forward start

You may terminate the VPN with the following commands
> killall openvpn ; pia-forward stop

**Comment by EricTheRed1** [comment] 2016-08-04 04:36
I ran all the commands successfully but I can't seem to pull up the openvpn.log.  At first I got permission denied when typing in /tmp/openvpn.log.  I can CD to the directory tmp but nothing happens when i type openvpn.log.  

Also, I contacted PIA and they do not support VM issues except on the forum.

**Comment by EricTheRed1** [comment] 2016-08-09 01:04
I sense you are deep in thought.....

**Comment by KaiserSoft** [comment] 2016-08-10 14:56
I am currently quite busy at work so I try not to work on computer related topics when I am off.

The file /tmp/openvpn.log is a text file. You should transfer it to your computer or you can look at it with 'vi /tmp/openvpn.log'
I suspect the issue is caused by running the VM on the same machine you use to later access the VPN connection. It is a setup I have removed from the current documentation since it requires messing with the routing table on some networks. 
Do you have an old computer lying around or maybe access to a RaspBerry Pi?

**Comment by EricTheRed1** [comment] 2016-08-12 03:24
I will try all your commands again but I just wanted to let you know about something.  I did a fresh install of Mac OS on a VM with the PIA application version 62; it also disconnects when connected to TCP but not on UDP.  I can at least use your VM on UDP now.

**Comment by nipsyuk** [comment] 2016-08-14 15:50
Hi All

Just to add my two penneth worth.

I've been having the same issue since I updated last Friday.  I have also since built a new vpn machine from from the image, and had exactly the same issues with that.

Changing from TCP to UDP didn't make a difference.
Nor did disabling the Daemon.


Rebooting or Restarting the FW was the only way I could get the vpn to reconnect but it dropped again within a few mins.

I've downgraded to git checkout -f 3da1d05  And it's all working again.

I run Vbox on a dedicated debian pc, and the vpn server is a guest connected with a bridged connection to the lan and an internal vbox network for the inside.  
Then my torrent pc is a guest on the internal lan.

I am wondering if its anything to do with the certificate changes that PIAmade in July.   Other users seem to have had issues with the  open vpn client since then.

https://www.privateinternetaccess.com/forum/discussion/21796/vpn-connection-failed-message-with-new-configuration-files


Cheers

Nipsy

Ps great bit of sw by the way!

Session log on new version:0
root@pia-tunnel:/opt# tail -f /pia/cache/session.log
Sun Aug 14 14:24:38 2016 UDPv4 link local: [undef]
Sun Aug 14 14:24:38 2016 UDPv4 link remote: [AF_INET]46.166.137.244:1198
Sun Aug 14 14:24:38 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Aug 14 14:24:39 2016 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1558', remote='link-mtu 1542'
Sun Aug 14 14:24:39 2016 WARNING: 'cipher' is used inconsistently, local='cipher AES-128-CBC', remote='cipher BF-CBC'
Sun Aug 14 14:24:39 2016 [de6884b2dc5c27332359dd7ddea09642] Peer Connection Initiated with [AF_INET]46.166.137.244:1198
Sun Aug 14 14:24:41 2016 TUN/TAP device tun0 opened
Sun Aug 14 14:24:41 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sun Aug 14 14:24:41 2016 /sbin/ifconfig tun0 10.122.1.10 pointopoint 10.122.1.9 mtu 1500
Sun Aug 14 14:24:41 2016 Initialization Sequence Completed

session log on old version
Sun Aug 14 16:13:37 2016 connecting to PIAudp/Netherlands
Sun Aug 14 16:13:37 2016 OpenVPN 2.2.1 i486-linux-gnu [SSL] [LZO2] [EPOLL] [PKCS11] [eurephia] [MH] [PF_INET6] [IPv6 payload 20110424-2 (2.2RC2)] built on Dec  1 2014
Sun Aug 14 16:13:37 2016 WARNING: file '/pia/login-pia.conf' is group or others accessible
Sun Aug 14 16:13:37 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:13:37 2016 LZO compression initialized
Sun Aug 14 16:13:37 2016 UDPv4 link local: [undef]
Sun Aug 14 16:13:37 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:13:37 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Aug 14 16:13:37 2016 [03a5750032c6c4d876fcfc7acbbe878c] Peer Connection Initiated with [AF_INET]46.166.188.218:1194
Sun Aug 14 16:13:40 2016 TUN/TAP device tun0 opened
Sun Aug 14 16:13:40 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sun Aug 14 16:13:40 2016 /sbin/ifconfig tun0 10.121.1.6 pointopoint 10.121.1.5 mtu 1500
Sun Aug 14 16:13:40 2016 Initialization Sequence Completed
Sun Aug 14 16:31:20 2016 read UDPv4 [EHOSTUNREACH]: No route to host (code=113)
Sun Aug 14 16:31:20 2016 read UDPv4 [EHOSTUNREACH]: No route to host (code=113)
Sun Aug 14 16:39:11 2016 [03a5750032c6c4d876fcfc7acbbe878c] Inactivity timeout (--ping-restart), restarting
Sun Aug 14 16:39:11 2016 SIGUSR1[soft,ping-restart] received, process restarting
Sun Aug 14 16:39:13 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:39:13 2016 Re-using SSL/TLS context
Sun Aug 14 16:39:13 2016 LZO compression initialized
Sun Aug 14 16:39:13 2016 UDPv4 link local: [undef]
Sun Aug 14 16:39:13 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:39:13 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:39:15 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:39:19 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:39:27 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:39:43 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:40:14 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:40:14 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:40:14 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:40:16 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:40:16 2016 Re-using SSL/TLS context
Sun Aug 14 16:40:16 2016 LZO compression initialized
Sun Aug 14 16:40:16 2016 UDPv4 link local: [undef]
Sun Aug 14 16:40:16 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:40:16 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:40:18 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:40:22 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:40:30 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:40:46 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:41:16 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:41:16 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:41:16 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:41:18 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:41:18 2016 Re-using SSL/TLS context
Sun Aug 14 16:41:18 2016 LZO compression initialized
Sun Aug 14 16:41:18 2016 UDPv4 link local: [undef]
Sun Aug 14 16:41:18 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:41:18 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:41:20 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:41:25 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:41:33 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:41:49 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:42:18 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:42:18 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:42:18 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:42:20 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:42:20 2016 Re-using SSL/TLS context
Sun Aug 14 16:42:20 2016 LZO compression initialized
Sun Aug 14 16:42:20 2016 UDPv4 link local: [undef]
Sun Aug 14 16:42:20 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:42:20 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:42:22 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:42:26 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:42:34 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:42:50 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:43:20 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:43:20 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:43:20 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:43:22 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:43:22 2016 Re-using SSL/TLS context
Sun Aug 14 16:43:22 2016 LZO compression initialized
Sun Aug 14 16:43:22 2016 UDPv4 link local: [undef]
Sun Aug 14 16:43:22 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:43:22 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:43:24 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:43:28 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:43:36 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:43:52 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:44:22 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:44:22 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:44:22 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:44:24 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:44:24 2016 Re-using SSL/TLS context
Sun Aug 14 16:44:24 2016 LZO compression initialized
Sun Aug 14 16:44:24 2016 UDPv4 link local: [undef]
Sun Aug 14 16:44:24 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:44:24 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:44:26 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:44:30 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:44:38 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:44:54 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:45:24 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:45:24 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:45:24 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:45:26 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:45:26 2016 Re-using SSL/TLS context
Sun Aug 14 16:45:26 2016 LZO compression initialized
Sun Aug 14 16:45:26 2016 UDPv4 link local: [undef]
Sun Aug 14 16:45:26 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:45:26 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:45:28 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:45:33 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:45:41 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:45:57 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:46:26 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:46:26 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:46:26 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:46:28 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:46:28 2016 Re-using SSL/TLS context
Sun Aug 14 16:46:28 2016 LZO compression initialized
Sun Aug 14 16:46:28 2016 UDPv4 link local: [undef]
Sun Aug 14 16:46:28 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:46:28 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:46:30 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:46:34 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:46:42 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:46:58 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:47:28 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:47:28 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:47:28 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:47:30 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:47:30 2016 Re-using SSL/TLS context
Sun Aug 14 16:47:30 2016 LZO compression initialized
Sun Aug 14 16:47:30 2016 UDPv4 link local: [undef]
Sun Aug 14 16:47:30 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:47:30 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:47:32 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:47:36 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:47:44 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:48:00 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:48:30 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:48:30 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:48:30 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:48:32 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:48:32 2016 Re-using SSL/TLS context
Sun Aug 14 16:48:32 2016 LZO compression initialized
Sun Aug 14 16:48:32 2016 UDPv4 link local: [undef]
Sun Aug 14 16:48:32 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:48:32 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:48:34 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:48:38 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:48:46 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:49:02 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:49:32 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:49:32 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:49:32 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:49:34 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:49:34 2016 Re-using SSL/TLS context
Sun Aug 14 16:49:34 2016 LZO compression initialized
Sun Aug 14 16:49:34 2016 UDPv4 link local: [undef]
Sun Aug 14 16:49:34 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:49:34 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:49:36 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:49:40 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:49:48 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:50:04 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:50:34 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:50:34 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:50:34 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:50:36 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:50:36 2016 Re-using SSL/TLS context
Sun Aug 14 16:50:36 2016 LZO compression initialized
Sun Aug 14 16:50:36 2016 UDPv4 link local: [undef]
Sun Aug 14 16:50:36 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:50:36 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:50:38 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:50:42 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:50:50 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:51:06 2016 write UDPv4 []: Operation not permitted (code=1)
Sun Aug 14 16:51:36 2016 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 14 16:51:36 2016 TLS Error: TLS handshake failed
Sun Aug 14 16:51:36 2016 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 14 16:51:38 2016 NOTE: OpenVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Sun Aug 14 16:51:38 2016 Re-using SSL/TLS context
Sun Aug 14 16:51:38 2016 LZO compression initialized
Sun Aug 14 16:51:38 2016 UDPv4 link local: [undef]
Sun Aug 14 16:51:38 2016 UDPv4 link remote: [AF_INET]46.166.188.218:1194
Sun Aug 14 16:51:38 2016 write UDPv4 []: Operation not permitted (code=1)

**Comment by nipsyuk** [comment] 2016-08-14 15:57
Dammit, just disconnected again!
Trying "git checkout -f a79be31"

**Comment by nipsyuk** [comment] 2016-08-14 18:00
eef7d69 seems to have fixed it!


Cheers
Chris

**Comment by nipsyuk** [comment] 2016-08-15 06:14
Aaannnnd  perhaps it didn't.   Certainly lasts longer though.

now trying 17072ab

Cheers
Chris

**Comment by nipsyuk** [comment] 2016-08-17 17:32
Oddly, it's just started working again for no apparent reason.   been up for 24hrs now.

Phew

**Comment by EricTheRed1** [comment] 2016-08-18 05:19
Yes, mine has been working on TCP for a few minutes now.  It usually cuts out way before that.  PIA must have done something.  I suppose the issue can be closed now.

**Comment by nipsyuk** [comment] 2016-08-19 15:32
It's just dropped again.  Suspiciously just as I start a torrent download.   And thinking about it, it started behaving when the last dl ended.

Just had another trawl through the PIA forum and looks like I am not alone.

https://www.privateinternetaccess.com/forum/discussion/2256/vpn-disconnects-whenever-i-start-torrenting/p3

**Comment by nipsyuk** [comment] 2016-08-19 15:57
I've just set my torrent client (deluge) to use the PIA socks proxy and it's downloading fine.


Very odd

**Comment by nipsyuk** [comment] 2016-08-19 16:04
Scratch that.   It "was" dl ing fine till I added a 2nd torrent.

**Comment by nipsyuk** [comment] 2016-09-07 12:35
I have found a work around (possibly if it doesnt stop working the moment I post this) by reverting to the legacy ovpn files.   probably not as secure but it does seem to work and also indicates to me that it is something to do with ciphers or certs.

I've downloaded  6gig via torrent since I did this which is 5.9gb more than i was manageing before!


wgett'd the legacy ovpn files from https://www.privateinternetaccess.com/openvpn/openvpn-ip-tcp.zip
unziped to /pia/openvpn/PIAleg
in the /pia/openvpn/PIAleg directory edit the ovpn (netherlands.ovpn) file the path to the password file

so it now looks like:- 
client
dev tun
proto tcp
remote 109.201.154.150 443
resolv-retry infinite
nobind
persist-key
persist-tun
cipher bf-cbc
auth sha1
tls-client
remote-cert-tls server
auth-user-pass /pia/login-pia.conf
comp-lzo
verb 1
reneg-sec 0
crl-verify crl.pem
ca ca.crt
disable-occ
~

**Comment by nipsyuk** [comment] 2016-09-07 13:46
well it's downloaded 20gig without a drop!

**Comment by homek1978** [comment] 2016-09-28 08:00
I am experiencing similar issues. I run pia-vpn in virtualbox on ubuntu. My downloads stop after a few seconds/minutes. I tried to roll back to an earlier version but now it says "invalid login data" and the page where I can input my PIA credentials is empty (not possible to enter any accounts). The password file in the /pia directory is filled. Any hints how to fix the issue?

**Comment by KaiserSoft** [comment] 2016-12-31 19:03
I have been able to reproduce the issue. This is not a bug. The connection is terminated by the ISP when it detects a connection with large file transfers to PIA and/or other torrent providers.

**Closed** 2016-12-31 19:04 UTC
Labels: invalid
